#!/bin/sh
. ./.venv/bin/activate

DST="./imgs/"
SCRIPT="./plot_csv.py"

[ -d "$DST" ] || mkdir -p $DST

##################################################################################
#   plot 2.1 Interference
##################################################################################

echo "plotting single slit"
$SCRIPT \
    --reg-mode=none \
    --outfile $DST/2.1_Interferenz.png \
    ./data/2.1_Interferenz.csv

$SCRIPT \
    --reg-mode=single \
    --mirror \
    --outfile $DST/2.1_Interferenz.fit.png \
    ./data/2.1_Interferenz.csv



##################################################################################
#   plot 2.3 Double Slit 
##################################################################################

echo "plotting double slit"
$SCRIPT \
    --reg-mode=none \
    --outfile $DST/2.2_Doppelspalt.png \
    ./data/2.2_doppelspalt.csv
# fit over double is not stable
$SCRIPT \
    --reg-mode=single_max \
    --mirror \
    --outfile $DST/2.2_Doppelspalt.fit.png \
    ./data/2.2_doppelspalt.csv

##################################################################################
#   plot 2.3 lloyd mirror
##################################################################################

echo "plotting lloyd mirror"
$SCRIPT \
    --reg-mode=none \
    --outfile $DST/2.3_lloydspiegel.png \
    ./data/2.3_lloydspiegel.csv

##################################################################################
#   plot 2.4 double generator
##################################################################################

echo "plotting double generator"
$SCRIPT \
    --reg-mode=none \
    --outfile $DST/2.4_doppelgenerator.png \
    ./data/2.4_doppelgenerator.csv

$SCRIPT \
    --reg-mode=single_max \
    --mirror \
    --outfile $DST/2.4_doppelgenerator.fit.png \
    ./data/2.4_doppelgenerator.csv

deactivate
